remote_theme: just-the-docs/just-the-docs
markdown: GFM
#Title
title: DDU
# External navigation links
nav_external_links:
  - title: Temaer
    url: https://digitaltdesignlyngby.github.io/#temaer
  - title: Projektarbejde
    url: https://digitaltdesignlyngby.github.io/#projektarbejde-i-ddu
  - title: Projekter og opgaver
    url: https://digitaltdesignlyngby.github.io/#projekter-og-forlb
