remote_theme: just-the-docs/just-the-docs
markdown: GFM
#Title
title: DDU
# Enable or disable heading anchors
heading_anchors: false
# External navigation links
nav_external_links:
  - title: Temaer
    hurl: https://digitaltdesignlyngby.github.io/#temaer
  - title: Projektarbejde
    url: https://digitaltdesignlyngby.github.io/#projektarbejde-i-ddu
  - title: Projekter og opgaver
    url: https://digitaltdesignlyngby.github.io/#projekter-og-forlb

###########################

#related_resources_title: Other Resources

#related_resources_list:

#- title: Forums
#  hurl: https://some.developer.forum.com/

#- title: More Documentation
#  hurl: https://more.documentation.company.com

#- title: Documentation Portal
#  hurl: https://my.documentation.portal
