remote_theme: just-the-docs/just-the-docs
markdown: GFM
#Title
title: DDU
# Enable or disable heading anchors
heading_anchors: false
# External navigation links
nav_external_links:
  - title: Temaer
    url: https://digitaltdesignlyngby.github.io/#temaer
    hide_icon: true
  - title: Projektarbejde
    url: https://digitaltdesignlyngby.github.io/#projektarbejde-i-ddu
    hide_icon: true
  - title: Projekter og forløb
    url: https://digitaltdesignlyngby.github.io/#projekter-og-forlb
    hide_icon: true
  - title: Værktøjer og sprog
    url: https://github.com/digitaltdesignlyngby/digitaltdesignlyngby.github.io#v%C3%A6rkt%C3%B8jer--sprog
    hide_icon: true
  - title: Karaktergivning
    url: https://github.com/digitaltdesignlyngby/digitaltdesignlyngby.github.io#karaktergivning
    hide_icon: true
